const fs = require('fs');

const conversions = {
    'src/app/api/users/profile/route.ts': 'import { NextResponse } from "next/server";\nexport async function GET() { return NextResponse.json({}); }',
    'src/app/api/user/stats/route.ts': 'import { NextResponse } from "next/server";\nimport { adminDb } from "@/lib/firebase/admin";\nexport async function GET(req: Request) {\n    try {\n        const { searchParams } = new URL(req.url);\n        const userId = searchParams.get("userId");\n        if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });\n        const doc = await adminDb.collection("users").doc(userId).get();\n        return NextResponse.json(doc.data()?.stats || {});\n    } catch (e) {\n        return NextResponse.json({ error: "Internal Error" }, { status: 500 });\n    }\n}',
    'src/app/api/user/settings/route.ts': 'import { NextResponse } from "next/server";\nimport { adminDb } from "@/lib/firebase/admin";\nexport async function GET(req: Request) {\n    try {\n        const { searchParams } = new URL(req.url);\n        const userId = searchParams.get("userId");\n        if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });\n        const doc = await adminDb.collection("users").doc(userId).get();\n        return NextResponse.json(doc.data()?.settings || { theme: "dark" });\n    } catch (e) {\n        return NextResponse.json({ error: "Internal Error" }, { status: 500 });\n    }\n}',
    'src/app/api/user/profile/route.ts': 'import { NextResponse } from "next/server";\nimport { adminDb } from "@/lib/firebase/admin";\nexport async function GET(req: Request) {\n    try {\n        const { searchParams } = new URL(req.url);\n        const userId = searchParams.get("userId");\n        if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });\n        const doc = await adminDb.collection("users").doc(userId).get();\n        return NextResponse.json(doc.data() || {});\n    } catch (e) {\n        return NextResponse.json({ error: "Internal Error" }, { status: 500 });\n    }\n}',
    'src/app/api/training/plan/route.ts': 'import { NextResponse } from "next/server";\nimport { adminDb } from "@/lib/firebase/admin";\nexport async function GET(req: Request) {\n    try {\n        const { searchParams } = new URL(req.url);\n        const userId = searchParams.get("userId");\n        if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });\n        const snapshot = await adminDb.collection("trainingPlans").where("userId", "==", userId).limit(1).get();\n        return NextResponse.json({ plan: snapshot.empty ? null : snapshot.docs[0].data() });\n    } catch (e) {\n        return NextResponse.json({ error: "Internal Error" }, { status: 500 });\n    }\n}',
    'src/app/api/fasting/analyze/route.ts': 'import { NextResponse } from "next/server";\nexport async function POST() { return NextResponse.json({ success: true }); }',
    'src/app/api/fasting/status/route.ts': 'import { NextResponse } from "next/server";\nimport { adminDb } from "@/lib/firebase/admin";\n\nexport async function GET(req: Request) {\n    try {\n        const { searchParams } = new URL(req.url);\n        const userId = searchParams.get("userId");\n        if (!userId) return NextResponse.json({ error: "Missing userId" }, { status: 400 });\n        \n        const snapshot = await adminDb.collection("users").doc(userId)\n            .collection("fasting_sessions").where("status", "==", "active").limit(1).get();\n            \n        return NextResponse.json({ activeSession: snapshot.empty ? null : { id: snapshot.docs[0].id, ...snapshot.docs[0].data() } });\n    } catch (e) {\n        return NextResponse.json({ error: "Failed" }, { status: 500 });\n    }\n}\n\nexport async function POST(req: Request) {\n    try {\n        const body = await req.json();\n        const { userId, action, goalHours, notes, media } = body;\n        \n        if (!userId || !action) return NextResponse.json({ error: "Missing fields" }, { status: 400 });\n        \n        await adminDb.collection("users").doc(userId).set({ uid: userId }, { merge: true });\n        const sessionsRef = adminDb.collection("users").doc(userId).collection("fasting_sessions");\n        \n        if (action === "start") {\n            await sessionsRef.add({\n                userId,\n                startTime: new Date().toISOString(),\n                goal: goalHours || 16,\n                status: "active"\n            });\n        } else if (action === "stop") {\n            const activeSnapshot = await sessionsRef.where("status", "==", "active").limit(1).get();\n            if (!activeSnapshot.empty) {\n                const doc = activeSnapshot.docs[0];\n                const startTime = new Date(doc.data().startTime).getTime();\n                const durationSeconds = Math.floor((Date.now() - startTime) / 1000);\n                \n                await doc.ref.update({\n                    endTime: new Date().toISOString(),\n                    duration: durationSeconds,\n                    notes: notes || null,\n                    media: media || null,\n                    status: "completed"\n                });\n                \n                // Add to history\n                await adminDb.collection("entries").add({\n                    userId,\n                    type: "Fasting",\n                    duration: durationSeconds,\n                    date: new Date(),\n                    mode: "fasting",\n                    notes: notes || "Fasting Session"\n                });\n            }\n        }\n        return NextResponse.json({ success: true });\n    } catch (e) {\n        return NextResponse.json({ error: "Failed to update" }, { status: 500 });\n    }\n}',
    'src/app/api/ai/coach/route.ts': 'import { NextResponse } from "next/server";\nexport async function POST() { return NextResponse.json({ success: true }); }',
    'src/app/api/activity/list/route.ts': 'import { NextResponse } from "next/server";\nimport { adminDb } from "@/lib/firebase/admin";\nexport async function GET(req: Request) {\n    try {\n        const { searchParams } = new URL(req.url);\n        const userId = searchParams.get("userId");\n        const limitParam = searchParams.get("limit");\n        if (!userId) return NextResponse.json({ error: "User ID required" }, { status: 400 });\n        \n        const limitVal = limitParam ? parseInt(limitParam) : 50;\n        const snapshot = await adminDb.collection("entries")\n            .where("userId", "==", userId)\n            .limit(limitVal)\n            .get();\n            \n        // Sorting manually since firestore needs composite index if we combine where and orderBy\n        let activities = snapshot.docs.map(doc => ({\n            id: doc.id,\n            ...doc.data(),\n            date: doc.data().date?.toDate ? doc.data().date.toDate() : doc.data().date\n        }));\n        \n        activities.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());\n        \n        return NextResponse.json({ \n            activities,\n            meta: { limit: limitVal, count: activities.length }\n        });\n    } catch (error: any) {\n        return NextResponse.json({ error: error.message || "Internal Server Error" }, { status: 500 });\n    }\n}',
    'src/app/api/activity/likes/route.ts': 'import { NextResponse } from "next/server";\nexport async function GET() { return NextResponse.json({ likes: [] }); }',
    'src/app/api/activity/like/route.ts': 'import { NextResponse } from "next/server";\nexport async function POST() { return NextResponse.json({ success: true }); }',
    'src/app/api/activity/comment/route.ts': 'import { NextResponse } from "next/server";\nexport async function POST() { return NextResponse.json({ success: true }); }',
    'src/app/api/testdb/route.ts': 'import { NextResponse } from "next/server";\nexport async function GET() { return NextResponse.json({ success: true }); }'
};

for (const [file, content] of Object.entries(conversions)) {
    if (fs.existsSync(file)) {
        fs.writeFileSync(file, content);
        console.log("Rewrote file:", file);
    } else {
        console.log("File not found:", file);
    }
}
